/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/UI/AppButton.vue')['default']
    AppFooter: typeof import('./src/components/core/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/core/AppHeader.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    'IIc:roundPersonPin': typeof import('~icons/ic/round-person-pin')['default']
    'IMaterialSymbols:personPinRounded': typeof import('~icons/material-symbols/person-pin-rounded')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
  }
}
